FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /parser_pdf/
RUN pip install --no-cache-dir -r /parser_pdf/requirements.txt

COPY . /parser_pdf/
WORKDIR /parser_pdf

CMD ["python", "parser_main.py"]
