FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /download/
RUN pip install --no-cache-dir -r /download/requirements.txt

COPY . /download/
WORKDIR /download

CMD ["python", "test.py"]
